### ISSUE TITLE
Initial disposable components adaptation (BoxShape, Material)

### ISSUE THREAD

**Issue by menduz** [decentraland/sdk#251]
In the new ECS, the concept of DisposableComponents (or SharedComponents) no longer exists. That means that components mapped to Resources like textures, models or meshes are now passed by value and not by reference.

The renderer, in this case Unity, needs to reuse the resources when possible. Example:

In pseudo-operations, the following example describes the CRDT operations and assertions to change the textures of a material:

```yaml
messages:
# entity 1 has the same material as entity 2, by val
- type: put-component
  entity: 1
  component: material
  data: { texture: "a.png" }
- type: put-component
  entity: 2
  component: material
  data: { texture: "a.png" }

# assert that entity 1 and 2 share the reference of the material, it should be reused
- type: assert
  operation: entity(1).material == entity(2).material

# change the texture of the material of the entity 1 by passing a new description of the material
- type: put-component
  entity: 1
  component: material
  data: { texture: "a new texture.png" }

- type: assert # assert that the texture is different by reference
  operation: entity(1).material != entity(2).material && entity(1).material.texture != entity(2).material.texture


# put back the original texture
- type: put-component
  entity: 1
  component: material
  data: { texture: "a.png" }

# assert that entity 1 and 2 share the reference of the material, it should be reused
- type: assert
  operation: entity(1).material == entity(2).material

```
